### ISSUE TITLE
Build failed; couldn't find "keys.plist" file

### ISSUE THREAD

**Issue by eliyazdi** [SpartaHack/SpartaHackII-iOS#28]
![screen shot 2016-02-09 at 16 21 11](https://cloud.githubusercontent.com/assets/1785818/12930944/34c227f0-cf49-11e5-9db3-a70a2b4e4c4a.png)

**Comment by cnmcgrath** [comment]
The keys.plist file is something you have to generate on your own. It contains the Parse API keys that this app uses and that's not something you should be committing to a public repository. See line 30 in AppDelegate.swift

**Comment by eliyazdi** [comment]
@cnmcgrath Ah, okay. Could you just explain to me how to add the Parse API keys? I'm new to iOS/Xcode, so an explanation would be extremely helpful :) Thanks!

**Comment by cnmcgrath** [comment]
You have to generate a new app with Parse.com by signing up for an account. Once your first app is up and running you'll be able to view the ParseAppKey and ParseClientKey. You'll need both in your keys.plist file. 

To build the spartahack app, you need to have cocoa pods installed so that you can download the library dependencies. Once that's done, cocoa pods generates a .xcworkspace file which you can use to build and run the app. 

Also note, the backend of this app is entirely dependent on Parse and requires you to have the necessary classes and class configuration. Parse is shutting down in 2017 so I don't recommend starting your project on that. 

For the most part this project is designed so that the data model can be changed without having to rewrite the controllers and it wouldn't be too much work to get the app working with some RESTful service.

**Comment by eliyazdi** [comment]
Alright, thank you very much!
